### ISSUE TITLE
请问ios工程提交前测试过吗？

### ISSUE THREAD

**Issue by lukegao** [EasyDarwin/EasyClient#9]
为什么会有如此多的编译错误？大量找不到定义的变量：

> /Users/luke/projects/EasyClient/iOS/EasyClient/VC/EasyNVR/EasyNVRVC.m:62:97: Use of undeclared identifier 'ScreenHeight'
/Users/luke/projects/EasyClient/iOS/EasyClient/VC/EasyNVR/EasyNVRVC.m:76:25: Property 'mj_header' not found on object of type 'UICollectionView *'
/Users/luke/projects/EasyClient/iOS/EasyClient/VC/EasyNVR/EasyNVRVC.m:76:38: Use of undeclared identifier 'MJRefreshNormalHeader'

**Comment by lukegao** [comment]
After spending several hours to fix errors in this project, I finally gave up.
Please do NOT commit unfinished work.

**Comment by penggy** [comment]
Sorry!
